// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MessagePackProfile.flatbuffers
{

using global::System;
using global::FlatBuffers;

public struct SampleModel1Array : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SampleModel1Array GetRootAsSampleModel1Array(ByteBuffer _bb) { return GetRootAsSampleModel1Array(_bb, new SampleModel1Array()); }
  public static SampleModel1Array GetRootAsSampleModel1Array(ByteBuffer _bb, SampleModel1Array obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SampleModel1Array __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SampleModel1Element? Elements(int j) { int o = __p.__offset(4); return o != 0 ? (SampleModel1Element?)(new SampleModel1Element()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ElementsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SampleModel1Array> CreateSampleModel1Array(FlatBufferBuilder builder,
      VectorOffset elementsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    SampleModel1Array.AddElements(builder, elementsOffset);
    return SampleModel1Array.EndSampleModel1Array(builder);
  }

  public static void StartSampleModel1Array(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddElements(FlatBufferBuilder builder, VectorOffset elementsOffset) { builder.AddOffset(0, elementsOffset.Value, 0); }
  public static VectorOffset CreateElementsVector(FlatBufferBuilder builder, Offset<SampleModel1Element>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateElementsVectorBlock(FlatBufferBuilder builder, Offset<SampleModel1Element>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartElementsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SampleModel1Array> EndSampleModel1Array(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SampleModel1Array>(o);
  }
  public static void FinishSampleModel1ArrayBuffer(FlatBufferBuilder builder, Offset<SampleModel1Array> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSampleModel1ArrayBuffer(FlatBufferBuilder builder, Offset<SampleModel1Array> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
